### ISSUE TITLE
.dat无法解密

### ISSUE THREAD

**Issue by dfaofeng** [Asnxthaony/Il2CppDumper-ZZZ#1]
![image](https://user-images.githubusercontent.com/14891398/183074031-7c53b815-68b8-4afc-8751-7a5ce4b05c70.png)
目前看来是加密状态,需要寻找秘钥解才行

**Comment by alphagocc** [comment]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/28982331/183134434-09722045-24fc-4364-8f27-a2e90838269c.png">

**Comment by alphagocc** [comment]
未加密

**Comment by dfaofeng** [comment]
需要指定.dat的全路径？？
